Import("env")


def source(file):
    return "#/src/" + file

env["source_files"] += [
    source("main.cpp"),
    source("app.cpp"),
    source("game.cpp")
]


# ImGui
SConscript("#/src/imgui/SConscript", exports="env")